### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by Samundra123** [prakhar1989/docker-curriculum#169]
I was tired of going though many materials online and this was the perfect one for me 

Thank you so much

**Comment by vaso123** [comment]
I would like to say a big thanks too!

Since this time I was afraid of docker, I do not know why, maybe just rote, I used native PHP/Apache2 or nginx.

As I read your tutorial, I've just say: Yes, this is how a tutorial should look.

Clear, step by step from scratch, detailed explanation and gives enough information to not lost in the dockers world anymore.

Thank you again.

If you allow me, later maybe I'd like to translate it to Hungarian, there are no clear documentation like this.

**Comment by prakhar1989** [comment]
Thank you @Samundra123 and @vaso123  for the kind words, I'm glad to hear you like the tutorial.

@vaso123 : Yes, feel free to translate this in any language as you wish. When you are done, let me know so that I can add that a link to the translated version from docker-curriculum.com
