### ISSUE TITLE
Image size is very big

### ISSUE THREAD

**Issue by vaso123** [prakhar1989/docker-curriculum#201]
I know this is not authors fail, I just try to find answer for my question.

I do exactly what was in the tutorial for the cat image. Image has builded, but it is 700MB.

Why is it, how can I avoid it?

**Comment by alysson-azevedo** [comment]
what is your SO and docker version?

**Comment by prakhar1989** [comment]
You are right that the current image sizes are large and that's because I've not optimized the images. There are quite a few ways on reducing docker image sizes but it's complicated and for the purposes of the tutorial, I wanted to keep things simple for newcomers. You should google for 'reduce docker image size' and you'll get a bunch of info on the same.
