### ISSUE TITLE
What is means "tty"

### ISSUE THREAD

**Issue by ilyasDevGit** [prakhar1989/docker-curriculum#235]
Hi all,

i'm new at Docker.

What is means "tty" here "....an interactive tty in the container." See page https://docker-curriculum.com/#what-is-docker-

Can you please explain it?

Br, ilyas

**Comment by prakhar1989** [comment]
It simply means that it creates an interactive shell so that you can interact with the container.  Here's an example from the [reference](https://docs.docker.com/engine/reference/commandline/run/#assign-name-and-allocate-pseudo-tty---name--it)

https://docs.docker.com/engine/reference/commandline/run/#assign-name-and-allocate-pseudo-tty---name--it
