### ISSUE TITLE
Running as a least-privileged user

### ISSUE THREAD

**Issue by csterritt** [prakhar1989/docker-curriculum#30]
Thanks for doing this!  It's a great start.

As of Docker 1.10, we got the ability to *NOT* run as root in the container.  This is a good thing for any number of reasons (security, etc.) so it should really be covered in any tutorial.  At least the "If you're feeling particularly adventurous you can try rm -rf bin in the container" won't work any more.

**Comment by prakhar1989** [comment]
Thanks for opening the issue, @csterritt! Can you provide me a few references for this? I'll give that a read and the update the tutorial as needed =)

**Comment by csterritt** [comment]
Hey @prakhar1989 -- thanks for being willing.

Probably the best place to start is the Docker security info page: https://docs.docker.com/engine/security/security/

There's a security configuration "best practices" guide from the Center for Internet Security: https://benchmarks.cisecurity.org/tools2/docker/CIS_Docker_1.6_Benchmark_v1.0.0.pdf

This presentation has some clues too: http://www.slideshare.net/Docker/docker-security-for-slide

Cheers!

**Comment by prakhar1989** [comment]
Great! Thanks for the links. When I have an update ready, I'll let you know so that you can have a look and give feedback! Thanks again!

**Comment by prakhar1989** [comment]
Hi @csterritt, apologies for the late update. I spent some time going through the links you've provided, and while it seems something very useful to know about, I'd argue that it might be considered an advanced usage of Docker.

My goal with the tutorial is to be welcoming to users who've had no experience with Docker and give them enough information to try it out. While security is definitely an very important consideration when you're using Docker in production, I believe that since the tutorial serves as a getting started guide, I feel that this can be left out.

Feel free to let me know what you feel about this.
