### ISSUE TITLE
Port inconsistencies

### ISSUE THREAD

**Issue by philerooski** [prakhar1989/docker-curriculum#38]
[Here](https://hub.docker.com/r/prakhar1989/catnip/) you specify that the catnip image should be run as so: 
`$ docker run -p 5000:5000 prakhar1989/catnip`  

But [here](https://prakhar.me/docker-curriculum/) you write the same expression like this: 
`$ docker run -p 8888:5000 prakhar1989/catnip`

Is there a reason for these inconsistencies? I was confused why connecting to port 5000 on localhost didn't work while following the tutorial in the second link, but eventually figured out that I could connect to port 8888.

**Comment by prakhar1989** [comment]
Hi @philerooski, thanks for raising the issue. The difference is minor actually - the command on docker registry is just to show the usage and so the port is arbitrary. You can choose to change it if you prefer.

In the tutorial, however, I purposefully choose two different ports so that its easier for users to follow which port is being published on what. Which is why I chose 8888. Again, even in this case you can change the port to something else.

Hope that clarifies.

**Comment by edmundadjei** [comment]
Hi,

I am on McOS and stepping through the tutorial.
literally running 

_docker run -p 8888:5000 prakhar1989/catnip_

and then going to 192.168.99.100:8888 fails with cannot connect.

My docker container is running.

One thing I did notice was that the static-site container works and it appears to be associated with two ports where as the catnip container does not work and appears to be associated with only one port.

$ docker ps
CONTAINER ID        IMAGE                     COMMAND             CREATED             STATUS              PORTS                                           NAMES
0928c5533867        prakhar1989/catnip        "python ./app.py"   11 minutes ago      Up 11 minutes       0.0.0.0:8888->5000/tcp                          youthful_archimedes
b94e268bbf23        prakhar1989/static-site   "./wrapper.sh"      About an hour ago   Up About an hour    0.0.0.0:32769->80/tcp, 0.0.0.0:32768->443/tcp   static-site


any ideas?

**Comment by edmundadjei** [comment]
ignore this, it's fixed. I reinstalled pip
