### ISSUE TITLE
Inclusion of Kubernetes?

### ISSUE THREAD

**Issue by aronchick** [prakhar1989/docker-curriculum#8]
Great curriculum! Any reason you didn't include Kubernetes? It's the most popular container orchestration platform - we're happy to help flesh this out :)

(disclosure, I work on Kubernetes)

**Comment by prakhar1989** [comment]
Hey  @aronchick, thanks for liking the tutorial. There are a few reasons why I didn't include Kubernetes -

1. I don't have any experience with it. I would be not be comfortable in teaching what I don't know :)
2. IMHO container orchestration is an advanced topic. In my case, I've been able to be productive knowing simply what I've mentioned in the tutorial. Since my target audience was beginners, I didn't want to overwhelm them and wanted to highlight how to deploy apps with the absolute minimum. 
3. Lastly, afaik, Kubernetes support on AWS is not exactly great. Hence deploying apps on AWS would require quite a bit of configuration which can again be daunting for beginners. I understand, GCE is an alternative but since I lack experience with it, I didn't include it.

Having said that, I completely understand the importance of knowing a container orchestration platform - especially if you're looking at production deployments. I am considering adding an advanced section (or another tutorial) where I want to talk about Docker Swarm and Kubernetes.

As soon as I get started on that, I'll let you know so that you can help me flesh it out.

Let me know if this makes any sense. :)

Thanks for creating the issue and going over the tutorial.

Best

**Comment by aronchick** [comment]
Totally get it - directly to your points:

1) Happy to help you get up to speed on Kubernetes :)
2) You included AWS ECS which is an orchestrator. Wasn't sure why you included one but not another.
3) I wasn't clear about your point about k8s on AWS being great - there are tens of thousands of projects using it, and setting it up is one line `export KUBERNETES_PROVIDER=aws; curl https://get.k8s.io | bash`. There's literally no configuration beyond that. Was there something else you wanted to do?

Please let me know if I can help.

**Comment by marcosmlopes** [comment]
+1 it would be nice to have Kubernetes added as well

**Comment by rihbyne** [comment]
Hi guys,
I recently started following this repository.
Can somebody also add to this guide on how does docker complement with
CoreOS. I recently read about Core OS which is a striped down Linux
distribution with no xorg server designed to play well with containers. It
uses Gentoo's portage tool for build and packaging.
Very cool though.

warms,
Rihan Pereira

**Comment by aamir1995** [comment]
+1
